---
- name: Open http and https ports
  shell: firewall-cmd --permanent --add-service=http ; firewall-cmd --permanent --add-service=https
  notify: restart firewalld

- name: Open ports 5222 and 5269 for push actions to Spacewalk proxy (WE MAY NOT NEED THIS)
  shell: firewall-cmd --permanent --add-port=5222/tcp ; firewall-cmd --permanent --add-port=5269/tcp
  notify: restart firewalld

- name: Configuring Spacewalk with an Answer file
  shell: spacewalk-setup --answer-file=/etc/ansible/roles/spacewalk/files/spacewalk-file
